name: Local-Airflow-Cluster Production Deploy

on:
  pull_request_review:
    types:
      - 'submitted'
    branches:
      - 'master'
      # - 'main'

env:
  from_branch: develop
  to_branch: master
  ludis_bucket: us-west1-ludis-airflow-97e54236-bucket

jobs:
  merge-branch-and-push:
    if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'master'
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo on the runner first
      - name: Checkout all
        uses: actions/checkout@v3
      # Merges develop into main
      - name: Merge develop -> master
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: '$from_branch' # develop
          target_branch: '$to_branch' # master
          github_token: ${{ github.token }}
      # DEBUG: Show the current folder
      - name: Echo current folder
        run: echo "$PWD"
      # DEBUG: Show the files in the current folder
      - name: Echo files in current folder
        run: find "${search_dir}" "${work_dir}" -mindepth 1 -maxdepth 1 -type f -print0 | xargs -0 -I {} echo "{}"
      # Authenticate with GCP
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.gcp_credentials }}'
      # Upload to the GCP Bucket
      - id: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: '.'
          destination: 'ludis-test-bucket-1/gcs/dags'
          process_gcloudignore: true